version: "3.7"
services:
        app:
            build:
                args:
                    user: alexander
                    uid: 1000
                context: ./
                dockerfile: Dockerfile
            image: nanocharger-api
            container_name: nanocharger-api-app
            restart: unless-stopped
            working_dir: /var/www/
            volumes:
                - ./:/var/www
            networks:
                - nanocharger-api

        db:
            image: mysql:8.0
            container_name: nanocharger-api-db
            restart: unless-stopped
            environment:
                MYSQL_DATABASE: ${DB_DATABASE}
                MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                MYSQL_PASSWORD: ${DB_PASSWORD}
                MYSQL_USER: ${DB_USERNAME}
                SERVICE_TAGS: dev
                SERVICE_NAME: mysql
            ports:
                - 3314:3306
            volumes:
                - ./mysql:/docker-entrypoint-initdb.d
            networks:
                - nanocharger-api

        nginx:
            image: nginx:alpine
            container_name: nanocharger-api-nginx
            restart: unless-stopped
            ports:
                - 9999:8888
            volumes:
                - ./:/var/www
                - ./nginx:/etc/nginx/conf.d
            networks:
                - nanocharger-api

        redis:
            image: redis:alpine
            container_name: myapp-redis
            command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
            volumes:
                - ./data/redis:/data
            ports:
                - "8002:6379"
            networks:
                - nanocharger-api

networks:
    nanocharger-api:
        driver: bridge
